---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "datastore.fullname" . }}
  labels:
    product: {{ template "datastore.name" . }}
    app: rookout
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      product: {{ template "datastore.name" . }}
  template:
    metadata:
      labels:
        product: {{ template "datastore.name" . }}
        app: rookout
    spec:
      containers:
        - name: {{ template "datastore.name" . }}
          image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
          env:
            - name: ROOKOUT_DOP_SERVER_MODE
              value: {{ .Values.datastore.serverMode | quote }}
            - name: ROOKOUT_DOP_AUTO_TLS_DOMAIN
              value: {{ .Values.datastore.autoTlsDomain | quote }}
            {{ if (eq .Values.datastore.serverMode "AUTOTLS") }}
            - name: ROOKOUT_DOP_ENABLE_FILE_LOGGER
              value: "False"
            {{ end }}
          ports:
            {{ if (ne .Values.datastore.serverMode "TLS") }}
            - containerPort: 80
            {{ end }}
            {{ if (ne .Values.datastore.serverMode "PLAIN") }}
            - containerPort: 443
            {{ end }}
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              {{ if (eq .Values.datastore.serverMode "PLAIN") }}
              port: 80
              {{ else }}
              port: 443
              {{ end }}
              {{ if (eq .Values.datastore.serverMode "AUTOTLS") }}
              host: {{ .Values.datastore.autoTlsDomain }}
              {{ end }}
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - mountPath: "/var/rookout/database/db"
              name: rookout-volume
            - mountPath: "/var/rookout/certs"
              name: rookout-volume
      volumes:
        - name: rookout-volume
          persistentVolumeClaim:
            claimName: rookout-data-on-prem-pvc