{{- if .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "datastore.name" . }}
    chart: {{ template "datastore.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.serviceAccount.name }}
{{- end }}