apiVersion: v1
kind: Service
metadata:
  name: {{ template "datastore.fullname" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if and ((index .Values.service.loadBalancerIP) (eq .Values.service.type "LoadBalancer")) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    product: {{ template "datastore.name" . }}  
  ports:
    {{ if (ne .Values.datastore.serverMode "TLS") }}
    - protocol: TCP
      port: 80
      targetPort: 80
      name: {{ printf "%s-http" (include "datastore.name" .) }}
    {{ end }}
    {{ if (ne .Values.datastore.serverMode "PLAIN") }}
    - protocol: TCP
      port: 443
      targetPort: 443
      name: {{ printf "%s-https" (include "datastore.name" .) }}
    {{ end }}
