version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Publish Helm charts to Github Pages
          command: cat publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: rookout/helm-charts
      - run:
          name: Verify - Controller Chart
          command: |
            alias helm=/tmp/helm/bin/linux-amd64/helm
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              helm repo add rookout https://helm-charts.rookout.com
              helm repo update
              helm repo list
              helm inspect rookout/controller
            fi