# Default values for datastore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rookout/data-on-prem
  pullPolicy: IfNotPresent

datastore:
  env: production
  autoTlsDomain: ''
  
service:
  type: ClusterIP
  port: 80
  loadBalancerIP: ''

ingress:
  enabled: True
  path: '/*'
  ingressClass: ''

resources:
  requests:
    cpu: 30m
    memory: 32Mi
  limits:
    cpu: 4000m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
