# Default values for datastore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rookout/data-on-prem
  pullPolicy: IfNotPresent

datastore:
  env: production
  serverMode: AUTOTLS
  publicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwMnFkMkJER1Z1Z2ludUtPT29wMwpJb0ZPZ1BBSUFzTXJrUnlxajVkWnZDT2FBcjR6VDBkeW81YUM4UUxQUVRha1JGYUdOR1dRcTc4RmlraWNlRVJvCkluMnZQUW9scXpiT1kwcVhLWHdMSlZ5TmwzZFhGVXJCSVdONnIveGk2UWo4OGJqOElpd0tnTlIvZ3BSaG82ZG0KbldpWUpja202bjYwV3dGcmpodGpXVllOWE9VWWRycEt2YVdsc2hHenVpbThOaUJBcXp1Q2EwOEorSWVzWHZRdwpSclZHQzFRTEpHZXJXeGRnVEUwS3duaUFLRVFCeFpJVXZVRXd0RmV1anZSdmlNRnd0WmdKV3BNQll4Mk9xR2Y1CklpVDJ1RXZFUmpXRWtXcG4zVkI1Wkg4QWhpR3F3TkxFNzExTzk4S2xRK2FSVlBUOEJZZHNWM2ZTZGVmZzZXNWUKRFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  autoTlsDomain: ''
  
service:
  type: ClusterIp
  port: 80
  loadBalancerIP: ''

ingress:
  enabled: True
  path: '/*'
  ingressClass: ''

resources:
  requests:
    cpu: 30m
    memory: 32Mi
  limits:
    cpu: 4000m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
