apiVersion: v1
appVersion: "0.5.12"
description: A Helm chart for Rookout Controller on Kubernetes
icon: https://app.rookout.com/static/rookout/img/logo.svg
name: controller
version: 0.2.1
home: "http://rookout.com/"
maintainers:
- name: Mickael Alliel
  email: mickael@rookout.com
