{{- if .Values.controller.token }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "controller.fullname" . }}
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      app: {{ template "controller.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "controller.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.controller.resources | indent 12 }}
          env:
            - name: ROOKOUT_TOKEN
              value: {{ .Values.controller.token | quote }}
            - name: ROOKOUT_LISTEN_ALL
              value: {{ .Values.controller.listenAll | quote }}
            - name: ROOKOUT_AGENT_MAX_CPU
              value: {{ .Values.controller.internalResources.limits.cpu | quote }}
            - name: ROOKOUT_AGENT_MAX_MEMORY
              value: {{ .Values.controller.internalResources.limits.memory | quote }}
          ports:
            - name: grpc
              containerPort: 7486
            - name: websocket
              containerPort: 7488
          livenessProbe:
            # https://github.com/kubernetes/kubernetes/issues/37218
            # K8S to date does not support multiple ports in probes
            tcpSocket:
              port: 7486
          initialDelaySeconds: 15
          periodSeconds: 20
{{- end -}}
