kind: Service
apiVersion: v1
metadata:
  name: {{ template "rookout.fullname" . }}
  labels:
    app: {{ template "rookout.name" . }}
    chart: {{ template "rookout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "rookout.name" . }}
    release: {{ .Release.Name }}

  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 7486
      targetPort: 7486
    - name: websocket
      protocol: TCP
      port: 7488
      targetPort: 7488