kind: Service
apiVersion: v1
metadata:
  name: {{ template "controller.fullname" . }}
  labels:
    app: {{ template "controller.name" . }}
    chart: {{ template "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "controller.name" . }}
    release: {{ .Release.Name }}

  type: ClusterIP
  ports:
    - name: websocket
      protocol: TCP
      port: 7488
      targetPort: 7488